import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Sheard/Navbar";
import Footer from "@/Components/Sheard/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OMAR FARUK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="wrapper">
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
